#!/bin/bash

# iXX=YYY --> assigns instrument YYY to channel XX

# Bank 000:

i00=000 # Yamaha Grand Piano
i01=001 # Bright Yamaha Grand
i02=002 # Electric Piano
#   003 # Honky Tonk
i03=004 # Rhodes EP
i04=005 # Legend EP 2
#   006 # Harpsichord
#   007 # Clavinet
#   008 # Celesta
#   009 # Glockenspiel
#   010 # Music Box
i05=011 # Vibraphone
i06=012 # Marimba
#   013 # Xylophone
i08=014 # Tubular Bells
#   015 # Dulcimer
#   016 # DrawbarOrgan          ++
i12=017 # Percussive Organ     +++
i10=018 # Rock Organ            ++
i11=019 # Church Organ
#   020 # Reed Organ            --
#   021 # Accordian
#   022 # Harmonica
#   023 # Bandoneon
#   024 # Nylon String Guitar
i13=025 # Steel String Guitar
#   026 # Jazz Guitar
#   027 # Clean Guitar
#   028 # Palm Muted Guitar
#   029 # Overdrive Guitar
i14=030 # Distortion Guitar
#   031 # Guitar Harmonics
#   032 # Acoustic Bass
i15=033 # Fingered Bass
#   034 # Picked Bass
#   035 # Fretless Bass
#   036 # Slap Bass
#   037 # Pop Bass
#   038 # Synth Bass 1
i07=039 # Synth Bass 2        ++
#   040 # Violin
#   041 # Viola
#   042 # Cello
#   043 # Contrabass
#   044 # Tremolo
#   045 # Pizzicato Section
#   046 # Harp
#   047 # Timpani
#   048 # Strings
#   049 # Slow Strings
#   050 # Synth Strings 1
#   051 # Synth Strings 2
#   052 # Ahh Choir
#   053 # Ohh Voices
#   054 # Synth Voice
#   055 # Orchestra Hit
#   056 # Trumpet
#   057 # Trombone
#   058 # Tuba
#   059 # Muted Trumpet
#   060 # French Horns
#   061 # Brass Section
#   062 # Synth Brass 1
#   063 # Synth Brass 2
#   064 # Soprano Sax
#   065 # Alto Sax
#   066 # Tenor Sax
#   067 # Baritone Sax
#   068 # Oboe
#   069 # English Horn
#   070 # Bassoon
#   071 # Clarinet
#   072 # Piccolo
#   073 # Flute
#   074 # Recorder
#   075 # Pan Flute
#   076 # Bottle Chiff
#   077 # Shakuhachi
#   078 # Whistle
#   079 # Ocarina
#   080 # Square Lead
#   081 # Saw Wave
#   082 # Calliope Lead
#   083 # Chiffer Lead
#   084 # Charang
#   085 # Solo Vox
#   086 # Fifth Sawtooth Wave
#   087 # Bass & Lead
#   088 # Fantasia
#   089 # Warm Pad
#   090 # Polysynth
#   091 # Space Voice
#   092 # Bowed Glass
#   093 # Metal Pad
#   094 # Halo Pad
#   095 # Sweep Pad
#   096 # Ice Rain
#   097 # Soundtrack
#   098 # Crystal
#   099 # Atmosphere
#   100 # Brightness
#   101 # Goblin
#   102 # Echo Drops
#   103 # Star Theme
#   104 # Sitar
#   105 # Banjo
#   106 # Shamisen
#   107 # Koto
#   108 # Kalimba
#   109 # BagPipe
#   110 # Fiddle
#   111 # Shenai
#   112 # Tinker Bell
#   113 # Agogo
#   114 # Steel Drums
#   115 # Woodblock
#   116 # Taiko Drum
#   117 # Melodic Tom
#   118 # Synth Drum
#   119 # Reverse Cymbal
#   120 # Fret Noise
#   121 # Breath Noise
#   122 # Sea Shore
#   123 # Bird Tweet
#   124 # Telephone
#   125 # Helicopter
#   126 # Applause
#   127 # Gun Shot

# Bank 008:

#   004 # Detuned EP 1
#   005 # Detuned EP 2
#   006 # Coupled Harpsichord
#   014 # Church Bell
#   016 # Detuned Organ 1
#   017 # Detuned Organ 2
#   019 # Church Organ 2
#   021 # Italian Accordion
#   024 # Ukulele
#   025 # 12 String Guitar
#   026 # Hawaiian Guitar
#   028 # Funk Guitar
#   030 # Feedback Guitar
#   031 # Guitar Feedback
#   038 # Synth Bass 3
#   039 # Synth Bass 4
#   040 # Slow Violin
#   048 # Orchestral Pad
#   050 # Synth Strings 3
#   061 # Brass 2
#   062 # Synth Brass 3
#   063 # Synth Brass 4
#   080 # Sine Wave
#   107 # Taisho Koto
#   115 # Castanets
#   116 # Concert Bass Drum
#   117 # Melo Tom 2
#   118 # 808 Tom

# Bank 009:

#   125 # Burst Noise

# Bank 016:

#   025 # Mandolin

# Bank 128:

#   000 # Standard
#   001 # Standard 1
#   002 # Standard 2
#   003 # Standard 3
#   004 # Standard 4
#   005 # Standard 5
#   006 # Standard 6
#   007 # Standard 7
#   008 # Room
#   009 # Room 1
#   010 # Room 2
#   011 # Room 3
#   012 # Room 4
#   013 # Room 5
#   014 # Room 6
#   015 # Room 7
#   016 # Power
#   017 # Power 1
#   018 # Power 2
#   019 # Power 3
#   024 # Electronic
#   025 # TR-808
#   032 # Jazz
#   033 # Jazz 1
#   034 # Jazz 2
#   035 # Jazz 3
#   036 # Jazz 4
#   040 # Brush
#   041 # Brush 1
#   042 # Brush 2
#   048 # Orchestra Kit


# Sending the new assignation:

echo prog 00 $i00 | nc -CN localhost 9800
echo prog 01 $i01 | nc -CN localhost 9800
echo prog 02 $i02 | nc -CN localhost 9800
echo prog 03 $i03 | nc -CN localhost 9800
echo prog 04 $i04 | nc -CN localhost 9800
echo prog 05 $i05 | nc -CN localhost 9800
echo prog 06 $i06 | nc -CN localhost 9800
echo prog 07 $i07 | nc -CN localhost 9800
echo prog 08 $i08 | nc -CN localhost 9800


# (i) Channel 9 results in a strange behavior:
# it shows having 128-xxx instead of 000-xxx
# but in fact it sounds the standard 128-000
# echo prog 09 $i09 | nc -CN localhost 9800

echo prog 10 $i10 | nc -CN localhost 9800
echo prog 11 $i11 | nc -CN localhost 9800
echo prog 12 $i12 | nc -CN localhost 9800
echo prog 13 $i13 | nc -CN localhost 9800
echo prog 14 $i14 | nc -CN localhost 9800
echo prog 15 $i15 | nc -CN localhost 9800

# Lets display new mapping:
echo channels | nc -CN localhost 9800



